# Generated by Django 4.2 on 2023-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_delivery_date_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TotalPrice',
            field=models.IntegerField(null=True),
        ),
    ]
